JetBrains/teamcity-docker-images

- configs/linux/Agent/Ubuntu/Ubuntu-sudo.Dockerfile
`buildagent` is the default user and the user with `sudo` access in the `sudo` flavored Docker containers.
> Correct the actual user for sudo agent image

- configs/linux/Server/Ubuntu/Ubuntu.Dockerfile
- generated/linux/Server/Ubuntu/18.04/Dockerfile
I have changed jdk files owner's uid to root, to fix:
```
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Container ID 3175151 cannot be mapped to a host ID
```
error, which I faced on Ubuntu 18.04 when I have trying to install TeamCity 2020.2.x. Previous versions (2019.x & 2020.1.x) installed ok on my PC.
There is also an [issue about it.](https://github.com/JetBrains/teamcity-docker-server/issues/39)
> [Hotifx] Fix teamcity-server installation on Ubuntu 18.04

- configs/linux/Agent/Ubuntu/Ubuntu.Dockerfile
Upgrade containerd from1.2.13-2 -> 1.4.4-1 to a more recent version due to increasing insues with 1.2.13
- Release notes https://github.com/containerd/containerd/releases/tag/v1.4.4
> Bump containerd.io version

- configs/linux.config
- configs/linux/Agent/Ubuntu/18.04/Ubuntu.Dockerfile.config
- configs/linux/Agent/Ubuntu/Ubuntu.Dockerfile
- configs/linux/Server/Ubuntu/18.04/Ubuntu.Dockerfile.config
- configs/linux/Server/Ubuntu/Ubuntu.Dockerfile
- configs/linux/Server/UbuntuARM/18.04/UbuntuARM.Dockerfile.config
- configs/linux/Server/UbuntuARM/UbuntuARM.Dockerfile
Hello! While trying out TeamCity with the Docker images I encountered that Git LFS is not installed automatically, so I had trouble trying out a Pipeline that requires it.
This PR simply installs the `git-lfs` package, available on both 20.04 and 18.04, and afterwards `git lfs install --system` is called.
I didn't upload the generated Dockerfiles because I wasn't able to properly make the end lines work with Git in those files.
I've also needed to update the p4 versions, otherwise the images were not building.
> Add Git LFS to Linux images

- dockerhub/teamcity-agent/README.md
It took me quite a while to realise that `linux-sudo` meant images with that tag suffix. I thought it was some other sort of image named `linux-sudo`. Hopefully this clarifies this.
> Clarified what is meant by linux-sudo

- configs/common.config
- configs/linux.config
- configs/linux/Agent/UbuntuARM/18.04-sudo/UbuntuARM-sudo.Dockerfile.config
- configs/linux/Agent/UbuntuARM/18.04/UbuntuARM.Dockerfile.config
- configs/linux/Agent/UbuntuARM/20.04-sudo/UbuntuARM-sudo.Dockerfile.config
- configs/linux/Agent/UbuntuARM/20.04/UbuntuARM.Dockerfile.config
- configs/linux/Agent/UbuntuARM/UbuntuARM-sudo.Dockerfile
- configs/linux/Agent/UbuntuARM/UbuntuARM-sudo.Dockerignore
- configs/linux/Agent/UbuntuARM/UbuntuARM.Dockerfile
- configs/linux/Agent/UbuntuARM/UbuntuARM.Dockerignore
- configs/linux/MinimalAgent/UbuntuARM/20.04/UbuntuARM.Dockerfile.config
- configs/linux/Server/UbuntuARM/20.04/UbuntuARM.Dockerfile.config
- configs/linuxARM.config
- configs/windows.config
As mentioned in quite a few YouTrack issues[^1], ARM support is rather lacklustre, as only the server and the minimal-agent is available for building, and none is present on DockerHub.
I made changes to make an ARM build of the teamcity-agent possible and consistent with other builds:
- created configuration files for both 18.04 and 20.04 UbuntuARM builds with _Perforce_ removed as it does not provide an arm64 binary as of now (2021.2/2273812)
- modified `linuxARM.config` with arm64 dotnet binaries
- modified `common.config`, `linux.config` and `windows.config` for more consistent dotnet descriptions
- 20.04 images now default to a tag that does not include aformentioned version number
- ~~added newly the generated files~~
[^1]: …
> TW-68887/better arm support

- tool/README.md
Within the stored DSL-based build configurations, we refer to some of the parameters stored within target TeamCity server.
In order to simplify potential configuration from the scratch, that would be useful to define parameters that must be configured, along with their convenient description.
> [Automation-9] Add documentation about parameters that shall be configured in TeamCity Server.

- .teamcity/generated/HubProject.kts
- .teamcity/generated/ImageValidation.kts
- .teamcity/generated/LocalProject.kts
- .teamcity/generated/PublishHubVersion.kts
- .teamcity/generated/PublishLocal.kts
- .teamcity/generated/PushHubLinux.kts
- .teamcity/generated/PushHubWindows.kts
- .teamcity/generated/PushLocalLinux1804.kts
- .teamcity/generated/PushLocalLinux2004.kts
- .teamcity/generated/PushLocalWindows1803.kts
- .teamcity/generated/PushLocalWindows1809.kts
- .teamcity/generated/PushLocalWindows1903.kts
- .teamcity/generated/PushLocalWindows1909.kts
- .teamcity/generated/PushLocalWindows2004.kts
- tool/TeamCity.Docker/TeamCityKotlinSettingsGenerator.cs
This pull request (PR) represents part of the changes originated related to validation of TeamCity Docker images.
The original PR - https://github.com/JetBrains/teamcity-docker-images/pull/43 - contains changes related to logic inside of the compiling code, such as automation framework, visualization script of build configuration DSL generator, while the current PR includes re-generated DSLs that we store inside of repository.
The pull requests were separated in purpose of more convenient review of the changes.
As for DSL generation, it includes enhanced tabulation, thus the file will be readable from Git sources without the need to manually reformat it.
> [Automation] Docker Image Validation - re-generated build configuration DSLs

- .teamcity/generated/ImageValidation.kts
- .teamcity/generated/PublishHubVersion.kts
- .teamcity/generated/PublishLocal.kts
- .teamcity/generated/PushHubLinux.kts
- .teamcity/generated/PushHubWindows.kts
- .teamcity/generated/PushLocalLinux2004.kts
- .teamcity/generated/PushLocalWindows1809.kts
- .teamcity/generated/PushLocalWindows2004.kts
- tool/TeamCity.Docker/GenerateCommand.cs
- tool/TeamCity.Docker/TeamCityKotlinSettingsGenerator.cs
As of January of 2023 (`2022.10.x` and earlier releases), TeamCity does not officially support the deployment on ARM-based processors.
The current repository provides Dockerfiles for the build of Docker images compatible with ARM architecture, which users could create for experimental purposes. While we would keep the related manifests within the repository, we would like to exclude the process of building and publishing such images from the build chain defined via Kotlin DSL until the official support is introduced.
> Disable build of ARM-based TeamCity Docker Images within Docker-related build chain

- .teamcity/generated/ImageValidation.kts
- tool/TeamCity.Docker/TeamCityKotlinSettingsGenerator.cs
Currently, the trigger responsible for the start up of Docker Image validation process doesn't have any filter explicitly. Therefore, the configuration would be triggered only in case any configuration within `default` branch would be finished.
Given our branch naming conventions, we must change it to development and release branches.
> Add custom branch filter (development, release) into image validation build trigger

- tool/automation/framework/README.md
- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/docker/hub/DockerRegistryAccessor.kt
Currently, automation framework skips validation of Docker Image in case it wouldn't be able to guarantee the images were built for the same platform.
```
jetbrains/teamcity-agent-staging:2022.10.2-windowsservercore-1809 - found previous image - 2022.10.1-windowsservercore-1809, but OS version is different - 10.0.17763.3887 and 10.0.17763.3650
```
While we would want to retain the warning message mentioned above, that'd be useful for us to still check it, since that would cover situations when base image had been changed, especially in case of Windows.
> Move Docker Image into validation even if OS sub-version does not match

- configs/linux.config
- context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
- context/generated/linux/Server/Ubuntu/18.04/Dockerfile
- context/generated/linux/Server/Ubuntu/20.04/Dockerfile
- context/generated/teamcity-agent.md
- context/generated/teamcity-server.md
Pull requests corresponds to [TW-79803 Update Perforce Package version (2022.2-2369846) within TeamCity Docker Images](https://youtrack.jetbrains.com/issue/TW-79803/Update-Perforce-Package-version-2022.2-2369846-within-TeamCity-Docker-Images).
The version of Perforce packages used within TeamCity Docker Images - `2022.2-2369846` - had been deprecated and removed from package registry on February 15th, 2023.
```
15:21:46   Reading state information...
15:21:46   E: Version '2022.2-2369846~focal' for 'helix-cli-base' was not found
15:21:46   E: Version '2022.2-2369846~focal' for 'helix-cli' was not found
```
This pull request introduces changes aimed at bumping up to a newer version of the affected package - `2022.2-2369846` -> `2022.2-2407422`, release on February 15th, 2023. 
Details …
> [2022.10.x] Upgrade Perforce package version: 2022.2-2369846 -> 2022.2-2407422

- README.md
In order to simplify the process of giving feedback, the following links to some of the communication channels have been added into repository's documentation, including [issue tracker](https://youtrack.jetbrains.com/issues/TW), [community forum](http://jb.gg/teamcity-forum) and documentation.
> [Documentation] Add explicit links to some of the core communication channels into README.md

- .teamcity/hosted/scheduled/build/TeamCityScheduledImageBuildWindows.kts
- context/scripts/Web.cs
During the build of Windows 18.09-based images, we use C#'s `WebClient` in order to download the required files, specifically: JDK, Git and other archives.
Throughout this process, the following exception might occur:
```
...
An exception occurred during a WebClient request.
Access to the path 'C:\jdk.zip' is denied.
jdk.zip  attempt #7   after 10s
jdk.zip  abort
```
The ` Access to the path is denied` exception is relatively misleading. It could occur due to the following reasons:
1. **Permissions**. The user that executes the script doesn't have write permissions. It's not our case, as the base image we're using doesn't have a separate `root` user, thus write access is granted.
2. **File permissions**. Target file is either locked, or sub-folders does not exist, or host's filesystem …
> [Windows 18.09-based build of images] Handle "Access to path is denied" exception.

- .teamcity/generated/ImageValidation.kts
- .teamcity/hosted/scheduled/build/TeamCityScheduledImageBuildWindows.kts
- tool/TeamCity.Docker/TeamCityKotlinSettingsGenerator.cs
The pull request is dedicated to changing the order for the build of Windows 1809 based TeamCity Docker images in order to prevent potential dependency issues.
> Re-order the queue of building images within automated scheduled build (Windows)

- dockerhub/teamcity-server/README.md
Pull request changes the documentation in order to provide details about running TeamCity Server Linux-based Docker Container with the use of HTTPS connection for traffic encryption.
> [TW-79103] Update documentation: default user, HTTPS configuration

- configs/windows/MinimalAgent/nanoserver/NanoServer1803.Dockerfile
- configs/windows/MinimalAgent/nanoserver/NanoServer1809.Dockerfile
- configs/windows/Server/nanoserver/NanoServer1803.Dockerfile
- configs/windows/Server/nanoserver/NanoServer1809.Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1803/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1809/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1903/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1909/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/2004/Dockerfile
- context/generated/windows/Server/nanoserver/1803/Dockerfile
- context/generated/windows/Server/nanoserver/1809/Dockerfile
- context/generated/windows/Server/nanoserver/1903/Dockerfile
- context/generated/windows/Server/nanoserver/1909/Dockerfile
- context/generated/windows/Server/nanoserver/2004/Dockerfile
- context/scripts/Program.cs
Java Runtime within TeamCity Docker Images is being updated.
* Windows NanoServer Images: [Amazon Corretto JRE 8.252.09.2](https://corretto.aws/downloads/resources/8.252.09.2/amazon-corretto-8.252.09.2-windows-x64-jre.zip) -> [Amazon Corretto JDK 17.0.7.7.1](https://corretto.aws/downloads/resources/17.0.7.7.1/amazon-corretto-17.0.7.7.1-windows-x64-jdk.zip#MD5#feb7eab99c647a0b4347be9f0a3276de)
* The rest of the images (Linux, Windows Core):  [Amazon Corretto JDK 11.0.9.11.2](https://corretto.aws/downloads/resources/11.0.9.11.2/amazon-corretto-11.0.9.11.2-windows-x64-jdk.zip#MD5#9757ebcd8094b4d7040886b2c98bcf37) -> [Amazon Corretto JDK 17.0.7.7.1](https://corretto.aws/downloads/resources/17.0.7.7.1/amazon-corretto-17.0.7.7.1-windows-x64-jdk.zip#MD5#feb7eab99c647a0b4347be9f0a3276de)
Given …
> Replace JRE references with JDK @ NanoServer Images

- README.md
Currently, TeamCity Docker Images aren't provided for hosts with ARM-based architecture.
Until the development of Docker images for ARM-based architecture is complete (see: YouTrack tickets below), that would be useful to add a note about current state of the support, links that could be used to track the progress, and an option to try AMD-based TeamCity Docker image on an ARM-based host. 
- [[TW-74465] Teamcity-agent ARM64/v8](https://youtrack.jetbrains.com/issue/TW-74465/Teamcity-agent-ARM64-v8)
- [[TW-68887] Docker image. Support ARM architecture (AWS ECS Graviton ARM)](https://youtrack.jetbrains.com/issue/TW-68887/Docker-image.-Support-ARM-architecture-AWS-ECS-Graviton-ARM)
> [TEAMCITY-QA-T] Add a note on ARM support @ documentation

- .teamcity/generated/HubProject.kts
- .teamcity/generated/LocalProject.kts
- .teamcity/generated/PublishHubVersion.kts
- .teamcity/generated/PublishLocal.kts
- .teamcity/generated/PushHubLinux.kts
- .teamcity/generated/PushHubWindows.kts
- .teamcity/generated/PushLocalLinux1804.kts
- .teamcity/generated/PushLocalLinux2004.kts
- .teamcity/generated/PushLocalWindows1803.kts
- .teamcity/generated/PushLocalWindows1809.kts
- .teamcity/generated/PushLocalWindows1903.kts
- .teamcity/generated/PushLocalWindows1909.kts
- .teamcity/generated/PushLocalWindows2004.kts
- tool/TeamCity.Docker/TeamCityKotlinSettingsGenerator.cs
We would like to prevent situations when an AMD-based Docker Image would be attempted to be built on an ARM-based TeamCity Agent.
> [TEAMCITY-QA-T-289] Prevent build of AMD images on ARM agents

- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/docker/hub/DockerRegistryAccessor.kt
- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/docker/hub/auth/DockerhubCredentials.kt
Pull request is dedicated to prevention of NPE during an attempt to retrieve image size trend without explicit DockerHub credentials, e.g. for public repositories.
> [TEAMCITY-QA-T] Fix Docker Image size trend retrieval with empty credentials.

- configs/windows/Agent/nanoserver/NanoServer1803.Dockerfile
- configs/windows/Agent/nanoserver/NanoServer1809.Dockerfile
- configs/windows/Agent/windowsservercore/WindowsServerCore1803.Dockerfile
- configs/windows/MinimalAgent/nanoserver/NanoServer1803.Dockerfile
- configs/windows/MinimalAgent/nanoserver/NanoServer1809.Dockerfile
- configs/windows/Server/nanoserver/NanoServer1803.Dockerfile
- configs/windows/Server/nanoserver/NanoServer1809.Dockerfile
- context/generated/windows/Agent/nanoserver/1803/Dockerfile
- context/generated/windows/Agent/nanoserver/1809/Dockerfile
- context/generated/windows/Agent/nanoserver/1903/Dockerfile
- context/generated/windows/Agent/nanoserver/1909/Dockerfile
- context/generated/windows/Agent/nanoserver/2004/Dockerfile
- context/generated/windows/Agent/windowsservercore/1803/Dockerfile
- context/generated/windows/Agent/windowsservercore/1809/Dockerfile
- context/generated/windows/Agent/windowsservercore/1903/Dockerfile
- context/generated/windows/Agent/windowsservercore/1909/Dockerfile
- context/generated/windows/Agent/windowsservercore/2004/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1803/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1809/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1903/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1909/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/2004/Dockerfile
- context/generated/windows/Server/nanoserver/1803/Dockerfile
- context/generated/windows/Server/nanoserver/1809/Dockerfile
- context/generated/windows/Server/nanoserver/1903/Dockerfile
- context/generated/windows/Server/nanoserver/1909/Dockerfile
- context/generated/windows/Server/nanoserver/2004/Dockerfile
- tool/TeamCity.Docker/DockerGraphFactory.cs
AWS EKS uses containerd as the default container runtime engine starting from K8s 1.24 or higher. See `https://aws.amazon.com/blogs/containers/all-you-need-to-know-about-moving-to-containerd-on-amazon-eks/.`
There is a bug in containerd that causes windows-based Docker images with unescaped backward slashes in Dockerfile to fail when starting them in K8s. See this bug report: `https://github.com/containerd/containerd/issues/5067`.
As a workaround, one can change the container runtime engine from containerd to dockerd, but dockerd is only available in AWS EKS for K8s clusters with version 1.23 or lower.
The publicly available TeamCity agent images should be fully compatible with the default EKS settings without forcing the users to search for the workarounds.
> [TW-82170] Windows-based Docker agent images are not compatible with containerd

- .teamcity/scheduled/build/TeamCityDockerImagesScheduledBuild.kts
The trigger alligns scheduled build configuration with potential planned (nightly) maintanence of TeamCity server.
> [TEAMCITY-QA-T] Adjust trigger for scheduled (nightly) build of Docker 

- .teamcity/generated/LocalProject.kts
- .teamcity/generated/PublishHubLatest.kts
- .teamcity/generated/PublishLocal.kts
- .teamcity/hosted/arm/PushStagingLinux2004_Aarch64.kts
Pull request is dedicated to include aarch64-based images into staging and production manifest for existing images, including Server, Minimal and Regular Agent.
> [TEAMCITY-QA-T] Add publishing of manifest for aarch64-based images

- configs/linux.config
- context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
- context/generated/linux/Server/Ubuntu/18.04/Dockerfile
- context/generated/linux/Server/Ubuntu/20.04/Dockerfile
- context/generated/teamcity-agent.md
- context/generated/teamcity-server.md
Current version of Perforce CLI - `2022.2-2407422` - have been removed from [Helix package registry](https://package.perforce.com/apt/ubuntu/dists/focal/release/binary-amd64/Packages). 
```
E: Version ‘2022.2-2407422~focal’ for ‘helix-cli’ was not found
```
Therefore, it must be updated within TeamCity Docker images.
> [TW] Update Perforce Client (p4) within TeamCity Docker images.

- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/common/constants/ValidationConstants.kt
- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/docker/hub/DockerRegistryAccessor.kt
- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/docker/validation/DockerImageValidationUtilities.kt
Pull request is dedicated to the change within algorithm for verification of Docker Image's size, including the enhanced lookup. Previous lookup had used the date of publishing as the most important criteria. Now, we equally treat both publishing criteria and the tag itself, e.g. `2023.05.2`, `2022.10`.
Therefore, in case any previous release will receive a new bugfix (e.g. `2022.10.5`), the logic for validation of image size for the recent releases (e.g. `2023.05.2`) will still work properly.
> [TEAMCITY-QA-T] Enhance automation for the verification of Docker Image's size

- dockerhub/teamcity-agent/README.md
- dockerhub/teamcity-minimal-agent/README.md
- dockerhub/teamcity-server/README.md
Running `apt-get update` inside the agent container to produce this error:
```
W: GPG error: http://package.perforce.com/apt/ubuntu focal InRelease: The following signatures were invalid: EXPKEYSIG 7123CB760FF18869 Perforce Software (Package Signing) <support+packaging@perforce.com>
E: The repository 'http://package.perforce.com/apt/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
> [TW-83304] Agent Docker image's apt package manager doesn't trust the key of the apt Perforce repository

- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/Automation.kt
- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/common/constants/ValidationConstants.kt
- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/common/network/HttpRequestsUtilities.kt
- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/docker/hub/DockerRegistryAccessor.kt
- tool/automation/framework/app/src/main/kotlin/com/jetbrains/teamcity/docker/validation/DockerImageValidationUtilities.kt
That'd be useful to have the ability to ignore `-staging` postfix, in order to compare the images with the ones located at Dockerhub.
> [TEAMCITY-QA-T] Add ability to ignore `-staging` postfix @ Size Validation

- .teamcity/scheduled/build/base/TeamCityScheduledImageBuildLinux_Base.kt
It must be possible to, optionally, execute scheduled build from any development branch.
Pull request is dedicated to the update of corresponding `branchSpec` property of images' VCS root.
> [TEAMCITY-QA-T] Update branch spec for the scheduled build of Docker images.

- .teamcity/scheduled/build/TeamCityScheduledImageBuildWindows.kts
The pull request is dedicated to adding a process for publishing Windows-based Docker images created within a scheduled build to a nightly repository.
> [TEAMCITY-QA-T] Include the publication of Windows-based images from the scheduled build into the nightly repository.

- README.md
Pull request removes outdated section related to ARM.
Linux-based ARM images are now supported by TeamCity.
> [TEAMCITY-QA-T] Remove outdated README section about unsupported ARM

- configs/devkit/linux/agent/Ubuntu.devkit.Dockerfile
Running Docker on an AMD host, unlike ARM, it's not possible to delete the previously declared volume - that would result into "Device or Resource is Busy", as the directory would be held by Docker mount.
As a workaround, in order to achieve DevKit's need - an image wit tooling, but without TeamCity inside - it's possible to delete folder's contents instead of a complete mounted directory.
> [TW] Address issue with volume deletion on AMD host @ DevKit

- configs/version.config
- configs/windows/Agent/nanoserver/2004/NanoServer1809.Dockerfile.config
- configs/windows/Agent/windowsservercore/2004/WindowsServerCore1803.Dockerfile.config
- configs/windows/MinimalAgent/nanoserver/2004/NanoServer1809.Dockerfile.config
- configs/windows/Server/nanoserver/2004/NanoServer1809.Dockerfile.config
- context/generated/teamcity-agent.md
- context/generated/teamcity-minimal-agent.md
- context/generated/teamcity-server.md
Pull request is deidcated to:
* The removal of Windows 2004-based images as "officially supported platform", given the deprecation of the OS and its corresponding replacement with Windows 2022.
* The update of `latest` tag for 2023.11 verison.
> [Documentation @ 2023.11.x] Remove Windows 2004 from supported platforms, update 'latest' tag

- configs/windows/Agent/nanoserver/NanoServer2022.Dockerfile
- configs/windows/Agent/windowsservercore/WindowsServerCore2022.Dockerfile
- context/generated/windows/Agent/nanoserver/2022/Dockerfile
- context/generated/windows/Agent/windowsservercore/2022/Dockerfile
We copy TeamCity-related folders within the base agent image - `teamcity-minimal-agent`. However, once a new agent is built on top of it, the `permission denied` problem appears.
> [TCQA] Update permissions for regular Win2022 agents.

- configs/windows/Agent/nanoserver/NanoServer2022.Dockerfile
- configs/windows/Agent/windowsservercore/WindowsServerCore2022.Dockerfile
- context/generated/windows/Agent/nanoserver/2022/Dockerfile
- context/generated/windows/Agent/windowsservercore/2022/Dockerfile
Based on the status of PowerShell Module cache, the syntax of`icacls` execution at build time changes. 
When it is initialized, escaping should not be added(`nanoserver`); when it is not, it should be added (`windowsservercore`),  otherwise the build process will fail.
> [TCQA] Handle escaping based on PowerShell Module Cache Initialization @ Windows 2022

- configs/windows/Agent/nanoserver/NanoServer1803.Dockerfile
- configs/windows/Agent/nanoserver/NanoServer1809.Dockerfile
- configs/windows/Agent/nanoserver/NanoServer2022.Dockerfile
- configs/windows/Agent/windowsservercore/WindowsServerCore1803.Dockerfile
- configs/windows/Agent/windowsservercore/WindowsServerCore2022.Dockerfile
- configs/windows/MinimalAgent/nanoserver/NanoServer2022.Dockerfile
- configs/windows/Server/nanoserver/NanoServer2022.Dockerfile
- context/generated/windows/Agent/nanoserver/2022/Dockerfile
- context/generated/windows/Agent/windowsservercore/2022/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/2022/Dockerfile
- context/generated/windows/Server/nanoserver/2022/Dockerfile
Pull request is dedicated to cherry-pick the changes from https://github.com/JetBrains/teamcity-docker-images/pull/141 into `development/2023.11.x` branch.
> Cherry-pick into 2023.11.x: [TW] Windows 2022 Docker images: update the execution of file permission policies change 

- configs/linux.config
- configs/linux/Agent/Ubuntu/Ubuntu-sudo.Dockerfile
- configs/linux/Agent/Ubuntu/Ubuntu.Dockerfile
- configs/linux/Agent/UbuntuARM/UbuntuARM-sudo.Dockerfile
- configs/linux/Agent/UbuntuARM/UbuntuARM.Dockerfile
- context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/18.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/20.04/Dockerfile
- context/generated/teamcity-agent.md
Pull request is dedicated to the removal of `docker-compose` V1, which, according to Docker's [Docker Compose overview](https://docs.docker.com/compose/), is no longer receiving updates:
```
Effective July 2023, Compose V1 stopped receiving updates and is no longer in new Docker Desktop releases
```
`docker compose` plugin is bundled into `docker-ce-cli` currently available within the images. 
TeamCity supports both implementations.
> [TCQA] Remove out-of-support docker-compose V1, replacing with compose plugin bundled into "docker-ce-cli"

- configs/windows/MinimalAgent/nanoserver/NanoServer2022.Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/2022/Dockerfile
Pull request is aimed at enforcing case sensitivity within Windows 2022-based TeamCity Docker Images. This is necessary because the BuildAgent folder contains directories whose names are treated as case-sensitive by the application.
> [TW-87124] Enforce case sensitivity within Windows 2022 Docker Images

- configs/windows/MinimalAgent/nanoserver/NanoServer2022.Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/2022/Dockerfile
**Problem**
Windows 2022-based images become incompatible after the restart caused by the initial upgrade. The incompatibility is caused by the fact the plugin directories, which are being re-created upon the upgrade, receive the name in lowercase.
1. Upgrade, along with `plugins.zip`, is downloaded.
2. `plugins.zip` archive, containing the updated plugins, is extracted onto `C:\BuildAgent\plugins\` directory. Example: `testNGPlugin.zip`, `antPlugin.zip`, etc.
3. Plugins, which contains upper-cased letters in their names (such as `antPlugin`) are extracted into directories with lower-cased names, such as `antplugin`.
4. If a user will create the directory directly via PowerShell (`mkdir antPlugin`), it will also be created in lowercase (`antplugin`), while the custom directory …
> [TW-87124] Windows 2022-based Agent Images become incompatible with some runners after restart

- configs/windows/MinimalAgent/nanoserver/NanoServer1809.Dockerfile
- configs/windows/Server/nanoserver/NanoServer1809.Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1809/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1909/Dockerfile
- context/generated/windows/Server/nanoserver/1809/Dockerfile
- context/generated/windows/Server/nanoserver/1903/Dockerfile
- context/generated/windows/Server/nanoserver/1909/Dockerfile
Pull request is dedicated to the update of Windows 2019-related Dockerfiles, handling the inability to download the files onto `C:/` folder with `ContainerAdministrator` user. Simmilar changes are already applied to Windows 2022-based Dockerfiles.
Such situation may occur within specific environments.
> [TW] Adjust Windows 2019 Dockerfiles to infrastructure changes

- configs/linux.config
- context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
- context/generated/linux/Server/Ubuntu/18.04/Dockerfile
- context/generated/linux/Server/Ubuntu/20.04/Dockerfile
- context/generated/teamcity-agent.md
- context/generated/teamcity-server.md
The version of Perforce packages used within TeamCity Docker Images - '2022.2-2531894' - had been deprecated and removed from the package registry.
```
06:36:32   #7 33.89 E: Version '2022.2-2531894~focal' for 'helix-cli-base' was not found
06:36:32   #7 33.89 E: Version '2022.2-2531894~focal' for 'helix-cli' was not found
```
Therefore, it must be updated.
> [TW-89462] Update Perforce package version within TeamCity Docker Images: 2022.2-2531894 -> 2022.2-2637361

- configs/windows/MinimalAgent/nanoserver/NanoServer1809.Dockerfile
- configs/windows/MinimalAgent/nanoserver/NanoServer2022.Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1809/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1903/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/1909/Dockerfile
- context/generated/windows/MinimalAgent/nanoserver/2022/Dockerfile
- tool/agent-upgrade-dist/src/main/kotlin/Files.kt
Pull request is dedicated to:
* The use of `RealPath `instead of the canonical path within the utility designed for generating zip archives for the image build, helping to preserve the case of file and directory names.
* Bundling of plugins back into Windows-based images. Previously, agent relied on the upgrade and plugins sent by the server.
> [TW-90511] Update plugins within Windows-based docker images

- configs/linux.config
- context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/22.04/Dockerfile
- context/generated/linux/Server/Ubuntu/18.04/Dockerfile
- context/generated/linux/Server/Ubuntu/20.04/Dockerfile
- context/generated/linux/Server/Ubuntu/22.04/Dockerfile
- context/generated/teamcity-agent.md
- context/generated/teamcity-server.md
Helix CLI Core 2022.2-2637361 had been removed from the public package registry.
```
28.77 E: Version '2022.2-2637361~jammy' for 'helix-cli-base' was not found
06:39:31   28.77 E: Version '2022.2-2637361~jammy' for 'helix-cli' was not found
```
The version referenced in the Dockerfiles should be updated accordingly.
> TW-91535 Update Perforce Client within TeamCity Docker Images: 2022.2-2637361 -> 2022.2-2693782

- configs/linux.config
- configs/linuxARM.config
- configs/windows.config
- context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/22.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/18.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/20.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/22.04/Dockerfile
- context/generated/teamcity-agent.md
- context/generated/windows/Agent/nanoserver/1803/Dockerfile
- context/generated/windows/Agent/windowsservercore/1803/Dockerfile
- context/generated/windows/Agent/windowsservercore/1809/Dockerfile
- context/generated/windows/Agent/windowsservercore/1903/Dockerfile
- context/generated/windows/Agent/windowsservercore/1909/Dockerfile
- context/generated/windows/Agent/windowsservercore/2022/Dockerfile
- custom/linux/agent/amd/custom.dotnet.sdk.amd.Dockerfile
- custom/linux/agent/arm/custom.dotnet.sdk.arm.Dockerfile
- custom/windows/agent/custom.dotnet.sdk.win.amd.Dockerfile
Related: https://github.com/dotnet/core/issues/9671
> Update dotnetcli domain

- configs/linux/Agent/Ubuntu/22.04/Ubuntu.Dockerfile.config
- configs/linux/Agent/Ubuntu/Ubuntu.Dockerfile
- configs/linux/Agent/UbuntuARM/22.04/UbuntuARM.Dockerfile.config
- configs/linux/Agent/UbuntuARM/UbuntuARM.Dockerfile
- configs/linux/Server/Ubuntu/Ubuntu.Dockerfile
- configs/linux/Server/UbuntuARM/UbuntuARM.Dockerfile
- context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/22.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/18.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/20.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/22.04/Dockerfile
- context/generated/linux/Server/Ubuntu/18.04/Dockerfile
- context/generated/linux/Server/Ubuntu/20.04/Dockerfile
- context/generated/linux/Server/Ubuntu/22.04/Dockerfile
- context/generated/linux/Server/UbuntuARM/18.04/Dockerfile
- context/generated/linux/Server/UbuntuARM/20.04/Dockerfile
- context/generated/linux/Server/UbuntuARM/22.04/Dockerfile
Recently, Git 2.47.1 had been removed from Git's PPA (git-core/ppa), replacing it with the newer 2.48.0 version.
Unfortunately, the newer version includes an issue related to the fetch of the tags with shadow clones ([details](https://lore.kernel.org/all/CAM6buW5KSDGHD7txroqVa0TN_Ou_eV-LocMy06cPy0ZGDQmY9A@mail.gmail.com/T/)), preventing us from bundling it into the image, as it may affect the behavior of build steps.
Due to the open-source nature of TeamCity Docker Images, any non-publicly accessible mirrors cannot be used. Therefore, package-based installation had been replaced with the compilation from sources.
> [TW] Replace package-based Git installation with multistage build from sources to keep Git 2.47.1

- configs/linux.config
- configs/linux/Agent/Ubuntu/Ubuntu.Dockerfile
- configs/linux/Agent/UbuntuARM/UbuntuARM.Dockerfile
- configs/linux/Server/Ubuntu/Ubuntu.Dockerfile
- configs/linux/Server/UbuntuARM/UbuntuARM.Dockerfile
- context/generated/linux/Agent/Ubuntu/18.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/20.04/Dockerfile
- context/generated/linux/Agent/Ubuntu/22.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/18.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/20.04/Dockerfile
- context/generated/linux/Agent/UbuntuARM/22.04/Dockerfile
- context/generated/linux/Server/Ubuntu/18.04/Dockerfile
- context/generated/linux/Server/Ubuntu/20.04/Dockerfile
- context/generated/linux/Server/Ubuntu/22.04/Dockerfile
- context/generated/linux/Server/UbuntuARM/18.04/Dockerfile
- context/generated/linux/Server/UbuntuARM/20.04/Dockerfile
- context/generated/linux/Server/UbuntuARM/22.04/Dockerfile
Currently, TeamCity Docker images include Git LFS version 3.0.2 (included into the previous release), which is outdated. To incorporate the latest security fixes and features, we should update it to version 3.6.1.
> [TW-91666] Docker Images: update Git LFS (3.0.2 -> 3.6.1)

- configs/linux/MinimalAgent/Ubuntu/Ubuntu.Dockerfile
- configs/linux/MinimalAgent/UbuntuARM/UbuntuARM.Dockerfile
- configs/linux/Server/Ubuntu/Ubuntu.Dockerfile
- configs/linux/Server/UbuntuARM/UbuntuARM.Dockerfile
- context/generated/linux/MinimalAgent/Ubuntu/18.04/Dockerfile
- context/generated/linux/MinimalAgent/Ubuntu/20.04/Dockerfile
- context/generated/linux/MinimalAgent/Ubuntu/22.04/Dockerfile
- context/generated/linux/MinimalAgent/UbuntuARM/18.04/Dockerfile
- context/generated/linux/MinimalAgent/UbuntuARM/20.04/Dockerfile
- context/generated/linux/MinimalAgent/UbuntuARM/22.04/Dockerfile
- context/generated/linux/Server/Ubuntu/18.04/Dockerfile
- context/generated/linux/Server/Ubuntu/20.04/Dockerfile
- context/generated/linux/Server/Ubuntu/22.04/Dockerfile
- context/generated/linux/Server/UbuntuARM/18.04/Dockerfile
- context/generated/linux/Server/UbuntuARM/20.04/Dockerfile
- context/generated/linux/Server/UbuntuARM/22.04/Dockerfile
The issue addresses a regression [TW-91776](https://youtrack.jetbrains.com/issue/TW-91776) (`2024.12.1`), caused by incorrect locale within the AMD-based server containers.
> [TW-91776] Add the generation of the compiled locale data @ AMD images
